### ISSUE TITLE
Very large js file (2.4mB) causing panic

### ISSUE THREAD

**Issue by jackkleeman** [steveoc64/gopher-count#1]
I am getting "panic: runtime error: slice bounds out of range" every time I run gopher-count on my large js files (unminified and minified). I can send you this file in private if you need to replicate the issue.

Here is the trace:
`goroutine 1 [running]:
panic(0x4ac180, 0xc04200c040)
        C:/Go/src/runtime/panic.go:500 +0x1af
main.doCount(0xc042006680, 0x10)
        C:/Users/jackk/gopath/src/github.com/steveoc64/gopher-count/gopher-count.go:44 +0x4bf
main.main()
        C:/Users/jackk/gopath/src/github.com/steveoc64/gopher-count/gopher-count.go:11 +0x82`

**Comment by steveoc64** [comment]
Hi jack, thanks for having a play with the analyzer.

I have updated the README to reflect that it will only work with minified output in its current form, due to the simple assumptions it makes about the structure of the compiled output.

Its falling over on a line that assumes that it is on the start of a line, and there are at least 11 bytes left in the file ... a dangerous assumption :)  

I just ran a couple of extra test cases on it : 

1. A 7 MB chunk of minified javascript that is part of a game engine.  That worked fine with no errors.
2. A smaller chunk of minified javascript that is built against  https://github.com/oskca/gopherjs-vue.  This one is interesting because the gopherjs compiler includes a copy of vue.js in the compiled output ... as per this spec : https://github.com/gopherjs/gopherjs/wiki/Bundle-additional-JavaScript-with-Go-packages

That worked with no errors either.  I didnt realize that you could bundle JS libs in the compiled output like, which is a very useful feature.

Anyway - If you can send me a cp of that compiled & minified output, I will run it against that and reproduce the error.  Should be a simple fix, and it will make the analyzer a bit more robust.

Just fwd it straight through to steveoc64@gmail.com and I will take it from there. Thx.

**Comment by steveoc64** [comment]
Ping @jackkleeman - how did you go ?

**Comment by jackkleeman** [comment]
Hi @steveoc64, I sent you an email from jackkleeman@gmail.com on the 3rd.

**Comment by steveoc64** [comment]
My bad - gmail had dutifully placed that one in spam.   On to it now, brb.

**Comment by steveoc64** [comment]
@jackkleeman - this commit addresses your case.
https://github.com/steveoc64/gopher-count/commit/6808cad0cf6ebf11185779e0bc42fefe6941c85e

If that works for you, you can close the issue, ta.

This is a lib that you are compiling, in that it doesnt have a "main" function ?  ... I made the assumption that the compiled code has a "main" function, which is not always true. (eg - a lib)

Cheers.

**Comment by jackkleeman** [comment]
It actually just didn't have a main function because I hadn't written one yet, but yes, not everything has a main function. Thanks for helping me out, I will test to see if this works this evening.
